<<<<<<< HEAD
# Generated by Django 4.2.9 on 2024-01-12 11:02
=======
# Generated by Django 4.2.9 on 2024-01-12 09:00
>>>>>>> 174990fbae81e31da1807055262fef4c5720a0e3

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_kyc_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=4, max_length=7, prefix='', unique=True),
        ),
    ]
