# Generated by Django 4.2.8 on 2024-01-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='A staff', verbose_name='staff'),
        ),
    ]
