# Generated by Django 4.2.8 on 2023-12-17 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='A staff', verbose_name='staff'),
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_of_kin', models.CharField(max_length=255)),
                ('bvn', models.CharField(max_length=11)),
                ('residential_address', models.TextField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('means_of_identification', models.CharField(choices=[('nin', 'National Identification Number (NIN)'), ('passport', 'International Passport'), ('voters_card', "Voter's Card"), ('drivers_license', "Driver's License")], max_length=20)),
                ('picture_upload', models.ImageField(blank=True, null=True, upload_to='kyc_pictures/')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
