# Generated by Django 4.2.8 on 2023-12-17 19:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_user_is_staff_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='+2348121277476', max_length=128, region=None, verbose_name='Phone Numer'),
        ),
    ]
