# Generated by Django 4.2.8 on 2023-12-18 12:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='nok_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+2348121277476', help_text='+2348121277476', max_length=128, region=None, verbose_name='Next of Kin Phone Numer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+2348121277476', help_text='+2348121277476', max_length=128, region=None, verbose_name='Phone Numer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kyc',
            name='bvn',
            field=models.CharField(help_text='Enter a valid bvn number', max_length=11, unique=True, verbose_name='Bank verification Number'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='means_of_identification',
            field=models.CharField(choices=[('nin', 'National Identification Number (NIN)'), ('passport', 'International Passport'), ('voters_card', "Voter's Card"), ('drivers_license', "Driver's License")], help_text='Select a valid means of Identification', max_length=20, verbose_name='Bank verification Number'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='next_of_kin',
            field=models.CharField(help_text='Enter your next of kin Name', max_length=255, verbose_name='Next of Kin Name'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='picture_upload',
            field=models.ImageField(help_text='Upload a picture the selected means of Identification', upload_to='kyc_pictures/', verbose_name='Bank verification Number'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='residential_address',
            field=models.TextField(help_text='Enter full residential address', verbose_name='Residential Address'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='Select your gender', max_length=10, verbose_name='Sex'),
        ),
    ]
