services:
  - type: web
    name: main
    buildCommand: |
      pipenv install --deploy --ignore-pipfile
      python3 manage.py collectstatic --noinput
      python3 manage.py migrate
    startCommand: gunicorn main.wsgi:application