services:
  - type: web
    name: core
    buildCommand: |
      pipenv install --deploy --ignore-pipfile
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn main.wsgi:application