# Generated by Django 4.2.9 on 2024-02-01 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('failed', 'Failed'), ('completed', 'completed'), ('withdraw', 'Withdraw'), ('pending', 'Pending'), ('processing', 'Processing'), ('request_sent', 'Request Sent'), ('request_processing', 'Request Processing'), ('request_settled', 'Request Settled'), ('request_rejected', 'Rejected')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('recieved', 'Recieved'), ('withdraw', 'Withdraw'), ('refund', 'Refund'), ('payment_request', 'Payment Request'), ('none', 'None')], default='none', max_length=100),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', shortuuid.django_fields.ShortUUIDField(alphabet='12345678', length=15, max_length=20, prefix='CARD', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('card_type', models.CharField(choices=[('master', 'Master'), ('verve', 'Verve'), ('visa', 'Visa')], default='master', max_length=20)),
                ('card_status', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('card_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
