# Generated by Django 4.2.8 on 2023-12-15 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of your blog', max_length=255, verbose_name='Blog Title')),
                ('content', models.TextField(help_text='Write the content of your blog here')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Select the status of your blog', max_length=20)),
                ('slug', models.SlugField(help_text='Enter a URL-friendly title for your blog', max_length=255, unique=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='The number of times the blog has been viewed')),
                ('title_suggestion', models.TextField(blank=True, help_text='Suggestions for improving the title', null=True)),
                ('content_suggestion', models.TextField(blank=True, help_text='Suggestions for improving the content', null=True)),
                ('comments_suggestion', models.TextField(blank=True, help_text='Suggestions for managing comments', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created_at'],
                'permissions': [('can_create_post', 'Can create a new blog post'), ('can_edit_post', 'Can edit a blog post'), ('can_delete_post', 'Can delete a blog post'), ('can_view_post', 'Can view a blog post')],
            },
        ),
        migrations.CreateModel(
            name='Blog_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Write your comment here')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('blog_cmmented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.blog')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
