# Generated by Django 4.2.11 on 2024-03-17 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of your blog', max_length=255, verbose_name='Blog Title')),
                ('content', tinymce.models.HTMLField(help_text='Write the content of your blog here')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Select the status of your blog', max_length=20)),
                ('blog_category', models.CharField(choices=[('finance', 'Finance'), ('health', 'Health'), ('web_Design', 'Web Design'), ('technology', 'Technology'), ('banking_services', 'Banking Services'), ('investment', 'Investment'), ('financial_markets', 'Financial Markets'), ('credit_cards', 'Credit Cards'), ('mortgages', 'Mortgages'), ('online_banking', 'Online Banking'), ('personal_finance', 'Personal Finance'), ('business_finance', 'Business Finance')], default='draft', help_text='Select the category of your blog', max_length=20)),
                ('slug', models.SlugField(blank=True, help_text='Enter a URL-friendly title for your blog', max_length=255, null=True, unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Blog_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Write your comment here')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('blog_commented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.blog')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
