# Generated by Django 4.2.8 on 2023-12-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_comment',
            old_name='blog_cmmented',
            new_name='blog_commented',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='view_count',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('health', 'Health')], default='draft', help_text='Select the category of your blog', max_length=20),
        ),
    ]
