# Generated by Django 4.2.8 on 2023-12-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('health', 'Health'), ('web Design', 'Web Design'), ('html', 'HTML'), ('freebies', 'Freebies'), ('javaScript', 'JavaScript'), ('css', 'CSS'), ('tutorials', 'Tutorials')], default='draft', help_text='Select the category of your blog', max_length=20),
        ),
    ]
