# Generated by Django 4.2.8 on 2023-12-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
