# Generated by Django 4.2.8 on 2023-12-21 09:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=tinymce.models.HTMLField(help_text='Enter the title of your blog', max_length=255, verbose_name='Blog Title'),
        ),
    ]
