# Generated by Django 4.2.8 on 2023-12-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a URL-friendly title for your blog', max_length=255, null=True, unique=True),
        ),
    ]
