# Generated by Django 4.2.8 on 2023-12-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_post', 'Can create a new blog post'), ('can_edit_post', 'Can edit a blog post'), ('can_delete_post', 'Can delete a blog post'), ('can_view_post', 'Can view a blog post')], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AddField(
            model_name='blog',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
