# Generated by Django 4.2.8 on 2023-12-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blog_options_blog_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Enter the title of your blog', max_length=255, verbose_name='Blog Title'),
        ),
    ]
