# Generated by Django 4.2.8 on 2023-12-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='like_count',
        ),
    ]
