# Generated by Django 4.2.8 on 2023-12-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_image'),
        ('blog', '0018_alter_blog_options_alter_blog_blog_category'),
    ]

    operations = [
    ]
