# Generated by Django 4.2.8 on 2023-12-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_user_blog_author_alter_blog_image'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='blog',
        #     name='image',
        #     field=models.ImageField(blank=True, default='blog_img/default_image.jpg', null=True, upload_to='blog_img'),
        # ),
    ]
