# Generated by Django 4.2.8 on 2023-12-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_blog_image'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='blog',
        #     name='image',
        #     field=models.ImageField(blank=True, null=True, upload_to='blog_img'),
        # ),
    ]
